// <auto-generated />
namespace Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class colunas_add_estado : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(colunas_add_estado));
        
        string IMigrationMetadata.Id
        {
            get { return "201902010658040_colunas_add_estado"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
